# Generated by Django 3.2.6 on 2021-08-23 23:12

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('account', '0001_initial'),
        ('question', '__first__'),
    ]

    operations = [
        migrations.CreateModel(
            name='TakeAnswer',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('student_answer', models.TextField()),
                ('similarity', models.FloatField(null=True)),
                ('true_or_false', models.BooleanField(null=True)),
                ('question', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='question.question')),
                ('take_id', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='account.takequiz')),
            ],
        ),
    ]
